In [310]:
import pandas as pd
import numpy as np
from pathlib import Path

In [312]:
raw_shoppers = Path("../raw/dirty/online-shoppers-dirty.csv")

In [314]:
df_shoppers = pd.read_csv(raw_shoppers, sep=";")

In [316]:
df_shoppers.head()

,Unnamed: 0,Administrative,Administrative-Duration,INFORMATIONAL,Informational Duration,ProductRelated,ProductRelated Duration,Bouncerates,EXITRATES,PageValues,SpecialDay,Month,Operatingsystems,BROWSER,Region,TrafficType,VisitorType,Weekend,REVENUE
0,0,0,0.0,0,0.0,1,0.0,0.2,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,0,False
1,1,0,0.0,0,0.0,2,64.0,0.0,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,2,0,0.0,0,0.0,1,0.0,0.2,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,3,0,0.0,0,0.0,2,2.666666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,RETURNING,False,False
4,4,0,0.0,0,0.0,10,627.5,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [318]:
df_shoppers.columns

Index(['Unnamed: 0', ' Administrative ', 'Administrative-Duration',
       'INFORMATIONAL', 'Informational Duration', 'ProductRelated',
       ' ProductRelated Duration ', 'Bouncerates', 'EXITRATES', 'PageValues',
       'SpecialDay', ' Month ', 'Operatingsystems', 'BROWSER', 'Region',
       'TrafficType', ' VisitorType ', 'Weekend', 'REVENUE'],
      dtype='object')

In [320]:
df_shoppers.drop(columns=['Unnamed: 0'], inplace=True)

In [322]:
df_shoppers.shape

(12333, 18)

In [324]:
df_shoppers.dtypes

 Administrative               object
Administrative-Duration       object
INFORMATIONAL                  int64
Informational Duration       float64
ProductRelated                 int64
 ProductRelated Duration      object
Bouncerates                   object
EXITRATES                    float64
PageValues                    object
SpecialDay                   float64
 Month                        object
Operatingsystems               int64
BROWSER                        int64
Region                         int64
TrafficType                    int64
 VisitorType                  object
Weekend                       object
REVENUE                       object
dtype: object

In [326]:
df_shoppers.columns = [col.strip().lower() for col in df_shoppers.columns]

In [328]:
df_shoppers.columns

Index(['administrative', 'administrative-duration', 'informational',
       'informational duration', 'productrelated', 'productrelated duration',
       'bouncerates', 'exitrates', 'pagevalues', 'specialday', 'month',
       'operatingsystems', 'browser', 'region', 'traffictype', 'visitortype',
       'weekend', 'revenue'],
      dtype='object')

In [330]:
categorical_cols = ['administrative','administrative-duration','productrelated duration','bouncerates','month','pagevalues','visitortype','weekend', 'revenue']

In [332]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df_shoppers[col].unique())

Column: administrative
['0' '1' '2' '4' ' ?' '12' '3' '10' nan '6' '5' '9' '8' '16' '13' '11' '7'
 'unknown' '18' '14' '17' '19' '15' '24' '22' '21' '20' '23' '27' '26']

Column: administrative-duration
['0.0' '53.0' '64.6' ... '167.9107143' '305.125' '150.3571429']

Column: productrelated duration
['0.0' '64.0' '2.666666667' ... '465.75' '184.25' '346.0']

Column: bouncerates
['0.2' '0.0' '0.05' ... '0.003827751' '0.000869565' '0.011148992']

Column: month
['Feb' 'feb' '02' 'unknown' 'FEB' 'Mar' nan ' ?' 'May' '05' 'MAY' 'may'
 'Oct' 'June' 'Jul' 'Aug' 'Nov' 'nov' 'Sep' '11' 'NOV' 'Dec']

Column: pagevalues
['0.0' '54.17976426' '19.44707913' ... '78.81172527' '3.685400817'
 '12.24171745']

Column: visitortype
['Returning_Visitor' 'RETURNING' 'Returning Visitor' 'unknown'
 'returning_visitor' nan ' ?' 'New_Visitor' 'New Visitor' 'new_visitor'
 'NEW' 'Other']

Column: weekend
['0' 'False' 'True' ' ?' nan 'NO' 'YES' '1' 'unknown']

Column: revenue
['False' 'unknown' '0' 'True' 'NO' ' ?' '1' nan 'YES']

In [334]:
def clean_category(series: pd.Series) -> pd.Series:
    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
    )

In [336]:
for col in categorical_cols:
    df_shoppers[col] = clean_category(df_shoppers[col])

In [338]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df_shoppers[col].unique())

Column: administrative
['0' '1' '2' '4' '?' '12' '3' '10' 'nan' '6' '5' '9' '8' '16' '13' '11'
 '7' 'unknown' '18' '14' '17' '19' '15' '24' '22' '21' '20' '23' '27' '26']

Column: administrative-duration
['0.0' '53.0' '64.6' ... '167.9107143' '305.125' '150.3571429']

Column: productrelated duration
['0.0' '64.0' '2.666666667' ... '465.75' '184.25' '346.0']

Column: bouncerates
['0.2' '0.0' '0.05' ... '0.003827751' '0.000869565' '0.011148992']

Column: month
['feb' '02' 'unknown' 'mar' 'nan' '?' 'may' '05' 'oct' 'june' 'jul' 'aug'
 'nov' 'sep' '11' 'dec']

Column: pagevalues
['0.0' '54.17976426' '19.44707913' ... '78.81172527' '3.685400817'
 '12.24171745']

Column: visitortype
['returning_visitor' 'returning' 'returning visitor' 'unknown' 'nan' '?'
 'new_visitor' 'new visitor' 'new' 'other']

Column: weekend
['0' 'false' 'true' '?' 'nan' 'no' 'yes' '1' 'unknown']

Column: revenue
['false' 'unknown' '0' 'true' 'no' '?' '1' 'nan' 'yes']

In [340]:
df_shoppers.replace(
    {
        "?": np.nan,
        "unknown": np.nan,
        "nan": np.nan
        
    },
    inplace=True
)

In [342]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df_shoppers[col].unique())

Column: administrative
['0' '1' '2' '4' nan '12' '3' '10' '6' '5' '9' '8' '16' '13' '11' '7' '18'
 '14' '17' '19' '15' '24' '22' '21' '20' '23' '27' '26']

Column: administrative-duration
['0.0' '53.0' '64.6' ... '167.9107143' '305.125' '150.3571429']

Column: productrelated duration
['0.0' '64.0' '2.666666667' ... '465.75' '184.25' '346.0']

Column: bouncerates
['0.2' '0.0' '0.05' ... '0.003827751' '0.000869565' '0.011148992']

Column: month
['feb' '02' nan 'mar' 'may' '05' 'oct' 'june' 'jul' 'aug' 'nov' 'sep' '11'
 'dec']

Column: pagevalues
['0.0' '54.17976426' '19.44707913' ... '78.81172527' '3.685400817'
 '12.24171745']

Column: visitortype
['returning_visitor' 'returning' 'returning visitor' nan 'new_visitor'
 'new visitor' 'new' 'other']

Column: weekend
['0' 'false' 'true' nan 'no' 'yes' '1']

Column: revenue
['false' nan '0' 'true' 'no' '1' 'yes']

In [344]:
df_shoppers['month'].replace(     
    {
        "02": 'feb',
        "05": 'may',
        "11": 'nov'
        
    },
    inplace=True
)

df_shoppers['visitortype'].replace(     
    {
        'returning visitor': 'returning_visitor',
        "returning": 'returning_visitor',
        "new": 'new_visitor',
        "new visitor":'new_visitor'     
    },
    inplace=True
)

df_shoppers['weekend'].replace(     
    {
        '0': 'false',
        "1": 'true',
        "yes": 'true',
        "no":'false'     
    },
    inplace=True
)

df_shoppers['revenue'].replace(     
    {
        '0': 'false',
        "1": 'true',
        "yes": 'true',
        "no":'false'     
    },
    inplace=True
)

C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\2882179794.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers['month'].replace(
C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\2882179794.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers['visitortype'].replace(
C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\2882179794.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers['weekend'].replace(
C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\2882179794.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers['revenue'].replace(

In [346]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df_shoppers[col].unique())

Column: administrative
['0' '1' '2' '4' nan '12' '3' '10' '6' '5' '9' '8' '16' '13' '11' '7' '18'
 '14' '17' '19' '15' '24' '22' '21' '20' '23' '27' '26']

Column: administrative-duration
['0.0' '53.0' '64.6' ... '167.9107143' '305.125' '150.3571429']

Column: productrelated duration
['0.0' '64.0' '2.666666667' ... '465.75' '184.25' '346.0']

Column: bouncerates
['0.2' '0.0' '0.05' ... '0.003827751' '0.000869565' '0.011148992']

Column: month
['feb' nan 'mar' 'may' 'oct' 'june' 'jul' 'aug' 'nov' 'sep' 'dec']

Column: pagevalues
['0.0' '54.17976426' '19.44707913' ... '78.81172527' '3.685400817'
 '12.24171745']

Column: visitortype
['returning_visitor' nan 'new_visitor' 'other']

Column: weekend
['false' 'true' nan]

Column: revenue
['false' nan 'true']

In [348]:
numerical_cols = ['administrative','administrative-duration','productrelated duration','bouncerates','pagevalues']

In [350]:
for var in numerical_cols:
    print(f"\nColuna: {var}")
    print(df_shoppers[df_shoppers[var].astype(str).str.count(r"\.") > 1][var])

Coluna: administrative
Series([], Name: administrative, dtype: object)

Coluna: administrative-duration
271              0.0.0
297           171.25.0
320             38.0.0
397             13.5.0
617             40.0.0
1308             0.0.0
1385             0.0.0
2552             0.0.0
2578           109.0.0
2611             0.0.0
2806             0.0.0
2917             0.0.0
3004             0.0.0
3026             0.0.0
3065             0.0.0
3085             0.0.0
3326            14.0.0
3682            71.0.0
4102           222.5.0
4946             0.0.0
5064             0.0.0
5536     189.2646154.0
5544             0.0.0
5753             0.0.0
5781           124.6.0
6348           241.6.0
6824     230.3948365.0
7082     218.9666667.0
7222     34.26666667.0
7630           508.8.0
8643             0.0.0
9589           122.0.0
9609             0.0.0
9816            34.0.0
9916            38.5.0
10065            0.0.0
10290            0.0.0
10297           47.0.0
10604            0.0.0
10911            0.0.0
10946            0.0.0
11138           42.5.0
11208           31.0.0
11933            0.0.0
Name: administrative-duration, dtype: object

Coluna: productrelated duration
12             280.5.0
207            558.5.0
246            811.0.0
565      1361.166667.0
803             26.5.0
837       502.547619.0
1074            98.0.0
1401           163.0.0
1543     1272.916667.0
1841     684.7272727.0
1905     315.1666667.0
2089             0.0.0
2137     851.3333333.0
2604           639.5.0
2978     319.6666667.0
3103           815.0.0
3275            26.0.0
3361             0.0.0
3601           691.5.0
3934         2454.45.0
4286          3289.5.0
4753           959.0.0
5410     4126.353297.0
5457           120.4.0
6080     1685.747985.0
6259           342.0.0
6386     276.3666667.0
6436     809.4333333.0
6484         983.425.0
7317           123.3.0
7522     596.0333333.0
7755     504.0833333.0
7931            73.1.0
8039     5300.291667.0
8119     2556.373335.0
8181     2180.217803.0
9284     2366.192105.0
9501     2780.609524.0
9655            67.5.0
10168    13379.36658.0
10470         158.25.0
10987    4042.949908.0
11090           60.5.0
11185    1893.444444.0
11283    423.1666667.0
11962         253.25.0
Name: productrelated duration, dtype: object

Coluna: bouncerates
416              0.0.0
723              0.0.0
861              0.0.0
873              0.0.0
1063             0.0.0
1492             0.0.0
2043             0.0.0
2699     0.018181818.0
2860     0.005882353.0
3020     0.020588235.0
3239             0.0.0
3469          0.0375.0
3592             0.0.0
4073            0.08.0
4460             0.0.0
4548             0.0.0
5051     0.011627907.0
5155             0.2.0
5196            0.02.0
5880            0.05.0
6296     0.002959159.0
6754     0.010526316.0
6940             0.0.0
6962             0.0.0
7154             0.0.0
7645     0.011111111.0
7733             0.2.0
7896      0.00212766.0
8211             0.0.0
8263             0.0.0
8356             0.0.0
8932             0.0.0
8996     0.007407407.0
9471     0.016666667.0
9642             0.0.0
9882             0.0.0
9902             0.0.0
10241    0.006666667.0
10301     0.00931255.0
10496            0.0.0
10531            0.1.0
10746    0.019047619.0
11170    0.026666667.0
11616            0.0.0
11876            0.0.0
12247    0.010087719.0
Name: bouncerates, dtype: object

Coluna: pagevalues
237              0.0.0
685              0.0.0
1011             0.0.0
2096             0.0.0
3029     15.35760339.0
3194          51.176.0
3263             0.0.0
3280             0.0.0
3899          115.98.0
3907             0.0.0
4162     5.921482086.0
4343             0.0.0
4537             0.0.0
4638             0.0.0
5102             0.0.0
5491     51.03362522.0
5695             0.0.0
6600             0.0.0
6693             0.0.0
6710     26.41021956.0
6837             0.0.0
6844             0.0.0
7520             0.0.0
7900             0.0.0
7962             0.0.0
8126      25.7526389.0
8280             0.0.0
9038             0.0.0
9043     7.448242868.0
9121             0.0.0
9217             0.0.0
9317             0.0.0
9641             0.0.0
10257            0.0.0
10339    2.381971158.0
10563            0.0.0
10573            0.0.0
11337            0.0.0
11398            0.0.0
11473            0.0.0
11631    37.42337649.0
11739            0.0.0
11881            0.0.0
11955    38.83384563.0
12049    56.57877343.0
12281            0.0.0
Name: pagevalues, dtype: object

In [352]:
df_shoppers[numerical_cols] = df_shoppers[numerical_cols].replace(r"^(\d+\.\d+)\..*$", r"\1", regex=True).replace(r"[^\d.]", "", regex=True)

In [354]:
df_shoppers[numerical_cols]= df_shoppers[numerical_cols].apply(pd.to_numeric)

In [356]:
df_shoppers.dtypes

administrative             float64
administrative-duration    float64
informational                int64
informational duration     float64
productrelated               int64
productrelated duration    float64
bouncerates                float64
exitrates                  float64
pagevalues                 float64
specialday                 float64
month                       object
operatingsystems             int64
browser                      int64
region                       int64
traffictype                  int64
visitortype                 object
weekend                     object
revenue                     object
dtype: object

In [358]:
df_shoppers.isna().sum()

administrative             246
administrative-duration    244
informational                0
informational duration       0
productrelated               0
productrelated duration      0
bouncerates                  0
exitrates                    0
pagevalues                   0
specialday                   0
month                      246
operatingsystems             0
browser                      0
region                       0
traffictype                  0
visitortype                246
weekend                    246
revenue                    246
dtype: int64

In [360]:
cols_missing = ["administrative", "administrative-duration", "month", "visitortype", "weekend", "revenue"]

In [362]:
df_shoppers[cols_missing].isna().sum(axis=1).value_counts()

0    10930
1     1335
2       65
3        3
Name: count, dtype: int64

In [364]:
numerical_cols_miss_value = ["administrative","administrative-duration"]

In [366]:
for col in numerical_cols_miss_value:
    df_shoppers[col].fillna(df_shoppers[col].median(), inplace=True)

C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\3846194132.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers[col].fillna(df_shoppers[col].median(), inplace=True)

In [368]:
categorical_cols_miss_value = [ "month", "visitortype", "weekend", "revenue"]

In [370]:
for col in categorical_cols_miss_value:
    mode_value = df_shoppers[col].mode()

    if len(mode_value) > 0:
        df_shoppers[col].fillna(mode_value[0], inplace=True)
    else:
        df_shoppers[col].fillna("unknown", inplace=True)

C:\Users\ineko\AppData\Local\Temp\ipykernel_18944\2337224327.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_shoppers[col].fillna(mode_value[0], inplace=True)

In [372]:
df_shoppers.isna().sum().sum()

0

In [374]:
df_shoppers.duplicated().sum()

127

In [376]:
df_shoppers.drop_duplicates(inplace=True)

In [378]:
df_shoppers.dtypes

administrative             float64
administrative-duration    float64
informational                int64
informational duration     float64
productrelated               int64
productrelated duration    float64
bouncerates                float64
exitrates                  float64
pagevalues                 float64
specialday                 float64
month                       object
operatingsystems             int64
browser                      int64
region                       int64
traffictype                  int64
visitortype                 object
weekend                     object
revenue                     object
dtype: object

In [380]:
df_shoppers.columns

Index(['administrative', 'administrative-duration', 'informational',
       'informational duration', 'productrelated', 'productrelated duration',
       'bouncerates', 'exitrates', 'pagevalues', 'specialday', 'month',
       'operatingsystems', 'browser', 'region', 'traffictype', 'visitortype',
       'weekend', 'revenue'],
      dtype='object')

In [382]:
df_shoppers["source_file"] = "online-shoppers-dirty.csv"

In [384]:
df_shoppers.sample(5)

,administrative,administrative-duration,informational,informational duration,productrelated,productrelated duration,bouncerates,exitrates,pagevalues,specialday,month,operatingsystems,browser,region,traffictype,visitortype,weekend,revenue,source_file
2743,0.0,0.0,0,0.0,2,0.000000,0.200000,0.200000,0.0,0.0,may,1,1,3,11,returning_visitor,true,false,online-shoppers-dirty.csv
7296,2.0,13.0,0,0.0,66,2061.926508,0.013235,0.014203,0.0,0.0,jul,3,2,6,3,returning_visitor,false,false,online-shoppers-dirty.csv
2809,1.0,0.0,0,0.0,3,22.000000,0.066667,0.100000,0.0,0.8,may,2,2,1,6,returning_visitor,false,false,online-shoppers-dirty.csv
2310,0.0,0.0,0,0.0,33,663.233333,0.026471,0.059804,0.0,0.8,may,3,2,3,13,returning_visitor,false,false,online-shoppers-dirty.csv
867,0.0,0.0,0,0.0,12,425.166667,0.000000,0.016667,0.0,0.0,mar,1,1,6,10,returning_visitor,false,false,online-shoppers-dirty.csv

In [386]:
df_shoppers.to_csv("../raw/cleaned/online-shoppers-cleaned.csv", index=False)